### ISSUE TITLE
Where's the isu binary from?

### ISSUE THREAD

**Issue by coldnew** [alef78/intel-ifwi-study#1]
Hi, I'm really interest on this tool since I am trying to rebuild the Geeksphone Revolution's boot.img.
Can you tell me where you get the key.perm and isu binary ?

**Comment by coldnew** [comment]
mmm... I think isu is binary provide by Intel, right ? Is there anyway to calculate the key.pem from boot.img ?

**Comment by alef78** [comment]
isu binary was found here: https://github.com/alan-shen/sign_stitch_intel

key.pem was published by someone (I think it was Borqs developer) at pan.baidu.com. It can be used for Ramos i9 (non 3g version) and many its clones, Ramos i8c, and for some Teclast tablets.
There is no known way to calculate it from boot.img (it is RSA key used to sign boot.img, droidboot.img, recovery.img and logo.img).

**Comment by coldnew** [comment]
thanks :)

**Comment by pcwizzy37** [comment]
Is there a way I can grab the Borqs key currently?
